### ISSUE TITLE
Group/artifact ids in dependencies in cms pom.xml not correct

### ISSUE THREAD

**Issue by bcanvural** [diva-e/angular-bloomreach-integration#3]
Hi,

I was just building the project and saw that there were some build errors. It seems some group/artifact id names kept their old form during a refactoring. In cms pom i had to change:
    <dependency>
      <groupId>com.diva</groupId>
      <artifactId>netpioneer.myangularhippo-repository-data-config</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>com.diva</groupId>
      <artifactId>netpioneer.myangularhippo-repository-data-webfiles</artifactId>
      <version>${project.version}</version>
    </dependency>

to 

    <dependency>
      <groupId>com.diva-e</groupId>
      <artifactId>netpioneer.myangularhippo-repository-data-config</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>com.diva-e</groupId>
      <artifactId>myangularhippo-repository-data-webfiles</artifactId>
      <version>${project.version}</version>
    </dependency>

and in site pom:
    <dependency>
      <groupId>com.diva</groupId>
      <artifactId>netpioneer.myangularhippo-angular</artifactId>
      <version>${project.version}</version>
      <type>pom</type>
    </dependency>

to 
    <dependency>
      <groupId>com.diva-e</groupId>
      <artifactId>myangularhippo-angular</artifactId>
      <version>${project.version}</version>
      <type>pom</type>
    </dependency>

**Comment by jpralle** [comment]
Hey,

thanks for the info. I wonder why it still is being built on my machine without any problems or missing updates to e.g. webfiles. But you are right, the dependencies are wrong. It now doesn't build in my machine, so I have to take a deeper look and see if there is another error hidden beneath it. Once I got that sorted out, I'll push a fix.

**Comment by bcanvural** [comment]
It must be your local maven cache. Just try renaming your m2 folder to m3 or something temporarily and have maven regenerate the local deps. That should help reproducing it. Once done you can rename the folder back to its original name

**Comment by jpralle** [comment]
I finally found the issue. The artifact if of repsitory-data-config was containing also the organisation id. I removed it and then your proposed change worked. I just pushed it, should be fixed now.
